agents:
  queue: "engaging"

steps:
  - label: "Install mpi4py"
    command:
      conda install -c conda-forge mpi4py -y 
  - label: "Run python files"
    command: |
      cd mpi4py
      mpirun -np 4 python p2p-array.py
      mpirun -np 4 python p2p-send-recv.py
  - label: "Submit Job"
    command:
      sbatch p2p-job.sh
  
  # - label:  "Run Mujoco Python File"
  #   command: |
  #     cd mujoco
  #     python mujoco_test.py
 
  # - label: "Run Mojoco Script"
  #   command: |
  #     cd mujoco
  #     sbatch run_batch_engaging.sh

    