agents:
  queue: "engaging"

steps:
  - label:  "Run Mujoco Python File"
    command: python mujoco_test.py
 
  - label: "Run Mojoco Script"
    command: |
      cd mujoco
      sbatch run_batch_engaging.sh

    