agents:
  queue: "engaging"
  queue: "local"

steps:
  - label: "Load Modules on Engaging"
    command: |
      module use /orcd/software/community/001/modulefiles/rocky8/
      module load miniforge
      module load openmpi/4.1.4-pmi-ucx-x86_64 
    agents:
      queue: "engaging"
    skip: if queue != engaging
    
  - label: "Create Virutal Environment"
    # need openMPI to use pip install mpi4py (user install locally)
    command:
      # conda install -c conda-forge mpi4py -y 
      # python3 -m venv .venv
      # source .venv/bin/activate
      pip install numpy mpi4py
    key: "setup"
    agents:
      queue: "engaging"
      queue: "local"


  - label: "Run python files for agents running locally"
    command: |
      cd mpi4py
      mpirun -np 4 python p2p-array.py
      mpirun -np 4 python p2p-send-recv.py
    agents: 
      queue: "local"
    depends_on: "setup"
    skip: if queue != local

  - label: "Submit Job on Engaging using Sbatch"
    command:
      sbatch p2p-job.sh
    agents:
      queue: "engaging"
    depends_on: "setup"
    skip: "if queue != engaging"
  
  # - label:  "Run Mujoco Python File"
  #   command: |
  #     cd mujoco
  #     python mujoco_test.py
 
  # - label: "Run Mojoco Script"
  #   command: |
  #     cd mujoco
  #     sbatch run_batch_engaging.sh

    