agents:
  queue: "local"

steps:
  - label: "Create Virutal Environment"
    # need openMPI to use pip install mpi4py (user install locally)
    command: |
      whoami
      python3 -m venv .venv
      source .venv/bin/activate
      pip install numpy mpi4py
    key: "setup"

  - label: "Run python files for agents running locally"
    command: |
      cd mpi4py
      mpirun -np 4 python p2p-array.py
      mpirun -np 4 python p2p-send-recv.py
    depends_on: "setup"
   